BATCH_SIZE: 128
BUFFER_SIZE: 1000
CHANNELS: 1
EMBEDDING_DIM: 2
EPOCHS: 10
IMAGE_SIZE: 32
LEARNING_RATE: 1e-3
NETWORK_PARAMS:
  FEATURES: 2048
  KERNEL: 3
  LAYERS: 3
  STRIDE: 2
OPERATION_PARAMS:
  OPTIMIZER: SGD
VALIDATION_SPLIT: 0.2
