OP_SPEC:
  EMBEDDING_DIM: 2
  EPOCHS: 10
  BUFFER_SIZE: 1000
  VALIDATION_SPLIT: 0.2
DATASPEC:
  IMAGE_SIZE: 32
  CHANNELS: 1
  BATCH_SIZE: 128
NETWORK_PARAMS:
  FEATURES: 2048
  KERNEL: 3
  LAYERS: 3
  STRIDE: 2
LEARNING_PARAMS:
  OPTIMIZER: Adam
  LEARNING_RATE: 1e-3
  LOSS_PARAM: mean
EXPERIMENT_PARAM:
  SummaryWriterPATH: .\runs\experiment_1
  TEST_SAMPLES: 5000
  MODEL_FILE: autoencoder_model.pth
  SUMMARYTXT: summary_text.txt
CLASSIFIER:
  HIDDEN: 64
  MODEL_FILE: classifier_model.pth