OP_SPEC:
  EMBEDDING_DIM: 200     #Dimension of Latents Vector
  EPOCHS: 15
  BUFFER_SIZE: 1000
  VALIDATION_SPLIT: 0.2
  KLDIVWEIGHT: 1.2
DATASPEC:
  DATA_DIR: 'CelebFaces/img_align_celeba/img_align_celeba/'
  DATA_FOLDER: 'CelebFaces'
  TRAINSET_RATIO: 0.8
  IMAGE_SIZE: 64
  CHANNELS: 3
  BATCH_SIZE: 128
NETWORK_PARAMS:
  FEATURES: 64
  KERNEL: 3
  LAYERS: 3
  STRIDE: 2
  BLOCKS: 5
LEARNING_PARAMS:
  OPTIMIZER: Adam
  LEARNING_RATE: 1e-3
  LOSS_PARAM: mean
EXPERIMENT_PARAM:
  SummaryWriterPATH: runs
  TEST_SAMPLES: 5000
  MODEL_FILE: vae_celeb_model.pth 
  SUMMARYTXT: summary_text.txt
  TEXTWRITEMODE: w
  FLOAT_PRECISION: high
  TORCH_COMPILE: eager
CLASSIFIER:
  HIDDEN: 64
  MODEL_FILE: classifier_model.pth